language: python
python: 3.8
sudo: false

install:
  - pip install mkdocs==1.1
  - pip install git+https://github.com/CraftTweaker/mkdocs-use-site-url-plugin.git
  - pip install mkdocs-minify-plugin==0.2.3
  - pip install git+https://github.com/linkchecker/linkchecker.git


script:
  - mkdocs build --clean --site-dir site
  - linkchecker site/index.html --ignore-url="search\.html"

cache: pip
