commit_message: '[ci skip]'
files:
  - source: /docs/**/*.*
    ignore:
      - '*.sh'
      - '*.js'
      - '*.css'
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%
  - source: ./docs.json
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%
    type: txt
  - source: /docs_exported
    ignore:
      - '*.js'
      - '*.css'
      - '*.sh'
      - /**/docs.json
    translation: >-
      /translations_exported/%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs_exported/**/docs.json
    translation: >-
      /translations_exported/%two_letters_code%/%original_path%/%original_file_name%
    type: txt
