- Modyfikacje:
    - Contenttweaker:
      - API:
        - BracketHandlers: 'mods/contenttweaker/API/BracketHandlers.md'
        - Api:
          - IIsBuilder: 'mods/contenttweaker/API/api/IIsBuilder.md'
        - Zablokowanie:
          - BlockBuilder: 'mods/contenttweaker/API/block/BlockBuilder.md'
          - BlockTypeBuilder: 'mods/contenttweaker/API/block/BlockTypeBuilder.md'
          - Podstawowa:
            - BlockBuilderBasic: 'mods/contenttweaker/API/block/basic/BlockBuilderBasic.md'
          - Filar:
            - BlockBuilderPillarRotatable: 'mods/contenttweaker/API/block/filar/BlockBuilderPillarRotatable.md'
          - Schody:
            - BlockBuilderStairs: 'mods/contenttweaker/API/block/stairs/BlockBuilderStairs.md'
        - Element:
          - Konstruktor przedmiotów: 'mods/contenttweaker/API/item/ItemBuilder.md'
          - ItemTypeBuilder: 'mods/contenttweaker/API/item/ItemTypeBuilder.md'
          - MCItemGroup: 'mods/contenttweaker/API/item/MCItemGroup.md'
          - MCToolType: 'mods/contenttweaker/API/item/MCToolType.md'
          - Podstawowa:
            - ItemBuilderBasic: 'mods/contenttweaker/API/item/basic/ItemBuilderBasic.md'
          - Narzędzie:
            - ItemBuilderTool: 'mods/contenttweaker/API/item/tool/ItemBuilderTool.md'

- Vanilla:
    - Api:
      - Zablokowanie:
        - Materiał:
          - MCMaterial: 'vanilla/api/block/material/MCMaterial.md'
          - Kolor MCMaterialColor: 'vanilla/api/block/material/MCMaterialColor.md'
      - Bloki:
        - MCBlock: 'vanilla/api/blocks/MCBlock.md'
        - MCBlockState: 'vanilla/api/blocks/MCBlockState.md'
      - Nawiasy:
        - KomendStringDisplayable: 'vanilla/api/brackets/CommandStringDisplayable.md'
      - Util:
        - MCResourceLocation: 'vanilla/api/util/MCResourceLocation.md'

